import { createNewSrsState } from '../../../srs/srsEngine';
import { normalizeStoreData } from '../../storeDataNormalization';
import {
  deserializeCardDoc,
  deserializeDeckDoc,
  deserializeStudyModeDoc,
} from '../firestoreSchema';

function assertEqual<T>(actual: T, expected: T, message: string) {
  if (actual !== expected) {
    throw new Error(`${message}: expected ${String(expected)}, got ${String(actual)}`);
  }
}

function assertDeepEqual(actual: unknown, expected: unknown, message: string) {
  const actualJson = JSON.stringify(actual);
  const expectedJson = JSON.stringify(expected);
  if (actualJson !== expectedJson) {
    throw new Error(`${message}: expected ${expectedJson}, got ${actualJson}`);
  }
}

function assertThrows(fn: () => void, expectedMessagePart: string, message: string) {
  try {
    fn();
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    if (!errorMessage.includes(expectedMessagePart)) {
      throw new Error(`${message}: expected error containing "${expectedMessagePart}", got "${errorMessage}"`);
    }
    return;
  }

  throw new Error(`${message}: expected function to throw`);
}

export async function runTests() {
  console.log('\n--- Running Firestore Schema Tests ---');

  const card = deserializeCardDoc('card-1', {
    pages: ['hello', 'czesc'],
    srsState: createNewSrsState(),
  });

  const deck = deserializeDeckDoc(
    'deck-1',
    {
      name: 'Travel',
      activeModeId: 'classic',
      pageNames: 'broken',
      pageLanguages: ['en-US'],
      studyFilter: 'unsupported',
    },
    [card],
  );

  const normalized = normalizeStoreData({
    groups: [deck],
    studyModes: [
      deserializeStudyModeDoc('classic', {
        name: 'Classic',
        steps: [],
      }),
    ],
    activityHeatmap: {},
  });

  assertEqual(normalized.groups[0].activePageCount, 2, 'Missing activePageCount should normalize from surviving page arrays');
  assertDeepEqual(normalized.groups[0].pageNames, ['Page 1', 'Page 2'], 'Missing page names should be regenerated by normalization');
  assertDeepEqual(normalized.groups[0].pageLanguages, ['en-US', 'en-US'], 'Missing page languages should be padded safely');
  assertEqual(normalized.groups[0].studyFilter, 'new+review', 'Invalid studyFilter should fall back to the default');

  assertThrows(
    () =>
      deserializeDeckDoc(
        'broken-deck',
        {
          activeModeId: 'classic',
          pageNames: ['Front', 'Back'],
          pageLanguages: ['en-US', 'pl-PL'],
        },
        [],
      ),
    'missing a valid name',
    'Strongly corrupted deck docs should surface an error',
  );
  assertThrows(
    () =>
      deserializeCardDoc('broken-card', {
        pages: ['hello', 'czesc'],
        srsState: { ...createNewSrsState(), repetitions: '2' },
      }),
    'srsState.repetitions',
    'Cards with invalid SRS state should fail before reaching runtime study logic',
  );

  console.log('Firestore schema tests passed');
}
